# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20161006_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userid',
        ),
    ]
